---
- name: Install python3, docker and docker-compose
  hosts: docker_server
  become: yes
  gather_facts: no

  vars_files:
    - vars

  tasks:
    - name: Install python3 and docker
      vars:
        ansible_python_interpeter: /usr/bin/python
      yum:
        name:
          - python3
          - docker
        update_cache: yes
        state: present

    - name: Install docker and docker-compose python module
      pip:
        name:
          - docker
          - docker-compose

    - name: Install docker compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{lookup('pipe', 'uname -s')}}-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x

    - name: Start docker
      systemd:
        name: docker
        state: started


- name: Add ec2-user to docker group
  hosts: docker_server
  become: yes

  tasks:
    - name: Add ec2-user to docker group (Adding a user to the group does not take effect immediately )
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Reconnect to server session
      meta: reset_connection


- name: Test docker pull
  hosts: docker_server

  tasks:
    - name: Pull redis
      docker_image:
        name: redis
        source: pull

- name: Start docker containers
  hosts: docker_server


  vars_files:
    - vars

  tasks:
    - name: Copy docker-compose file
      copy:
        src: docker-compose.yaml
        dest: "{{user_home_dir}}/docker-compose.yaml"

    - name: Copy variable environment file
      copy:
        src: .env
        dest: "{{user_home_dir}}/.env"

    - name: docker login
      docker_login:
        registry_url: https://index.docker.io/v1
        username: "{{docker_username}}"
        password: "{{docker_password}}"

    - name: Start containers from docker-compose
      docker_compose:
        project_src: "{{user_home_dir}}"

